name: Build and Deploy Wisecow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: poojasingh9490/wisecow

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        run: |
          IMAGE_SHA=${REGISTRY}/${IMAGE_NAME}:${GITHUB_SHA}
          IMAGE_LATEST=${REGISTRY}/${IMAGE_NAME}:latest
          docker build -t "${IMAGE_SHA}" -t "${IMAGE_LATEST}" .
          docker push "${IMAGE_SHA}"
          docker push "${IMAGE_LATEST}"

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubeconfig
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          mkdir -p "$HOME/.kube"
          echo "$KUBE_CONFIG_DATA" | base64 --decode > "$HOME/.kube/config"

      - name: Deploy manifests
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_SHA: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          KUBE_NAMESPACE: wisecow
        run: |
          kubectl apply -k k8s
          kubectl -n "${KUBE_NAMESPACE}" set image deployment/wisecow wisecow="${IMAGE_SHA}"
          kubectl -n "${KUBE_NAMESPACE}" rollout status deployment/wisecow
